### ISSUE TITLE
Some notes what to fix from the course

### ISSUE THREAD

**Issue by theorashid** [rmp15/sharp_bayesian_environmental_health_2023#35]
## bayesian regression and temporal modelling

~`beta_year_exp` in bayesian regression and temporal modelling lecture and practical~

~In the temporal modelling practical `code_weekly_random_walk_with_temperature_by_month` says `# prior for alpha (Gary: make -inf +inf )`~

It's a bit weird that the model isn't converging. The model is correctly identified correctly. There's a weird residual out left that is the first data point. That's why alpha isn't converging – `lograte[1] <- alpha` as `rw[1] <- 0`. But it doesn't make sense to me why alpha wouldn't converge. ~Gary suggests to try `dflat()`.~ Weird though

The monthly temperature random effect is wrong. It's set up like a random walk but isn't a random walk. It should be
``` diff
-beta_temperature_month[1] <- 0
-for (m in 2:n_months) {
-  beta_temperature_month[m] ~ dnorm(0, sigma_temperature)
-}
+for (m in 1:n_months) {
+  beta_temperature_month[m] ~ dnorm(0, sigma_temperature)
+}
```

## Hierarchical modelling

~Liza's lecture outline slide: should say `complete pooling` and `partial pooling` as the golden middle.~

Normal model: common variance slide does not need IG prior

## Software options

~It should be `ArviZ` styled like `posterior`~

~Lab. Stan code, `vector[N] province`~

**Comment by rmp15** [comment]
Figured it out just put rw[0] <- alpha
